### ISSUE TITLE
Client calls apis.google.com/u/0/_rpctoken=25799367

### ISSUE THREAD

**Issue by amalic** [FoldingAtHome/fah-web-client#12]
Looks like you're tracking users. This is in my opinion a GDPR violation. 

Fix this ASAP please!

**Comment by bmcivor** [comment]
yeah it is annoying, but reloading with a hard cache clear seems to get it going again for those who stumble across this issue in their searches for a solution

**Comment by beshur** [comment]
This is a token google API issue to continue communication with their services, not part of analytics.

Anyway those calls will not be present in the subsequent releases, as it was removed already.
