### ISSUE TITLE
Temporarily provide a "Coronavirus" option in the disease preferences

### ISSUE THREAD

**Issue by panos** [FoldingAtHome/fah-web-client#13]
A lot of people, myself included, have recently downloaded (or re-downloaded) FoldingAtHome, due to the amassed attention that it has received in the middle of the COVID-19 global pandemic, which is currently ongoing as of the time of this writing.

It would be great if people could focus on the particular goal that was the primary motivator that got them interested in the project in the first place, with the addition of an additional option that would allow this.

I have opened a similar issue for fah-control here: https://github.com/FoldingAtHome/fah-control/issues/47

**Comment by sopex** [comment]
The choice "Any" means Coronavirus. Not the best but a major update is a few weeks away and the option will be added. @jcoffland

**Comment by AlwaysLivid** [comment]
> The choice "Any" means Coronavirus. Not the best but a major update is a few weeks away and the option will be added. @jcoffland

Although Coronavirus projects are prioritized, there are other projects that get in the way.

**Comment by AlwaysLivid** [comment]
> The choice "Any" means Coronavirus. Not the best but a major update is a few weeks away and the option will be added. @jcoffland

Although Coronavirus projects are prioritized, there are other projects that get in the way.

**Comment by beshur** [comment]
The work units don't create themseves, so it's fine.

> The F@h team is working hard to generate as many new #COVID19 WUs as possible. In the meantime you may get a WU for another disease, and that’s okay! We care very deeply about addressing our current global health threat, but we also care about preventing future ones.

https://twitter.com/foldingathome/status/1242216518349475840

**Comment by shorttack** [comment]
Already fixed. Please try the beta at [](https://foldingathome.org/beta/) and report back here if you are still having this difficulty.
_Issue Support_

**Comment by anand-bhat** [comment]
The COVID-19 cause has been available as a choice since the v7.6.8 release (publicly available on April 17th, 2020).
