### ISSUE TITLE
Are contributions wanted?

### ISSUE THREAD

**Issue by tipsy** [FoldingAtHome/fah-web-client#15]
Hi,

I recently downloaded FAH again due to the ongoing coronavirus pandemic.

I noticed a few things could be improved in the current web-client UI, are you interested in contributions for this?

**Comment by Experiment8** [comment]
Same here, I was actually thinking more about a rewriting in more stable/modern tech stack, but no sure about the feasibility. Would be awesome to know some contribution guidelines.

**Comment by jcoffland** [comment]
We are working on a new client which will be fully Open-Source but things are a bit hectic right now.  We've had a massive increase in users in the last few days.  As soon as that gets under control we will focus on the Open-Source client.  Your contributions will be very welcome at that stage.

**Comment by DanFlannel** [comment]
So I got bored yesterday and spent the bulk of my time after work changing the front end over to use bootstrap (80% done). Have to re-setup the JS after, was wondering if you would want me to create a PR for that and give it over to you guys, wouldn't be too much more work to finish the rest of it. Was going to take a crack at the JS afterwards and clean it up for using the refreshed UI.

**Comment by RedactedProfile** [comment]
> Same here, I was actually thinking more about a rewriting in more stable/modern tech stack, but no sure about the feasibility. Would be awesome to know some contribution guidelines.

I was interested in doing just this too.  Imagine a world where there's several UI choices for web?

**Comment by M1ghtyboyPersonal** [comment]
> > Same here, I was actually thinking more about a rewriting in more stable/modern tech stack, but no sure about the feasibility. Would be awesome to know some contribution guidelines.
> 
> I was interested in doing just this too. Imagine a world where there's several UI choices for web?

i would love the ability to use a custom UI, current one is very buggy and refreshes 24/7

**Comment by fernanalegria** [comment]
I'm also willing to contribute in oder to build a modern version of the current FAH web client in case you finally decide to move on with this great idea.

**Comment by hamirmahal** [comment]
@jcoffland I think a lot of us are willing to contribute. Are there any places in particular where you want us to work?

**Comment by andrasfuchs** [comment]
@jcoffland Do you have any updates for us about the mentioned open-source client? 
What do you think is the best way to contribute? Do you guys have time to review and merge pull requests?

**Comment by jcoffland** [comment]
Contributions are welcome but you should look at the new Open-Source client.  I've just now made these repos public:

    https://github.com/FoldingAtHome/fah-web-client-bastet
    https://github.com/FoldingAtHome/fah-client-bastet

The new client is code named "bastet".  There is a front and back end.  The front end is a web client that is intended to run at https://app.foldingathome.org/ but you can also run it locally on your own web server at localhost.  We are getting ready to start alpha testing.  There's still a lot more work to do and documentation to write on how to get started but you're welcome to look around.  Report bugs or make PRs to those repos.

**Comment by andrasfuchs** [comment]
I just run the `fah-web-client-bastet` project, but I think I also need to run the `fah-client-bastet` to be able to see how the new web client looks like, right?

I got this (while my previously installed Folding@home service was running):
![image](https://user-images.githubusercontent.com/910321/141381599-037d154b-aa90-4fb9-bb34-513c47bed0f0.png)

Could you add a quick tutorial about compiling and running the new `fah-client-bastet` to [its readme](https://github.com/FoldingAtHome/fah-client-bastet/blob/master/README.md)?

**Comment by jcoffland** [comment]
I added a quick start guide for Debian Linux.  https://github.com/FoldingAtHome/fah-client-bastet  The Windows setup is more difficult and will take more time to document.

Let's move the conversation to the bastet repos.
