### ISSUE TITLE
FEATURE REQUEST: Finish button

### ISSUE THREAD

**Issue by kdb424** [FoldingAtHome/fah-web-client#3]
Would love to see a finish button added. It's available in the advanced client, and it would be great for when you want to control it from your phone.

**Comment by DubbySlashy** [comment]
You didn't read the previous issue, did you? There _is_ a Finish button. It just doesn't work like a Finish button.

**Comment by kdb424** [comment]
I completely missed that. Sorry for not noticing. Issue closed.
