### ISSUE TITLE
Wordpress CAPTCHA Plugin using F@H

### ISSUE THREAD

**Issue by Coernel82** [FoldingAtHome/fah-web-client#32]
Around every third website runs WordPress and most Websites have s.th. to be protected by a CAPTCHA.
Many solutions are very expensive for very small companies and many free ones such as Google ReCAPTCHA are not really free as you pay with your data and they are not GDPR-compliant.

So... why not program a CAPTCHA based on the proof of work concept:

- The CAPTCHA downloads data in the backend from the fah-servers.
- the client browser processes a small part of the data (for instance a 4 second workload for an average CPU)
- data gets sent back to server from the backend (to stay GDPR-compliant)

Thus a free and useful plugin can be provided fighting diseases and protecting websites from spam!

**Comment by jcoffland** [comment]
It's not possible to do anything usable for F@H in 4 seconds.  Running protein simulations requires uploading and downloading a significant amount of data.  And then performing some significant computation over a long enough period to make up for the cost of uploading and downloading.  Thanks for the suggestion though.
